from typing import Generator, Iterator

from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from jose import jwt, JWTError
from pydantic import ValidationError
from sqlalchemy.orm import Session

from app import models, schemas
from app import config

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/users/login")

def get_db() -> Iterator[Session]:
    try:
        db = config.SessionLocal()
        yield db
    finally:
        db.close()


async def get_current_user(
    db: Session = Depends(get_db), token: str = Depends(oauth2_scheme)
) -> models.User:
    credentials_exception = HTTPException(
      status_code=status.HTTP_401_UNAUTHORIZED,
      detail="Could not validate credentials",
      headers={"WWW-Authenticate": "Bearer"},
    )
    try:
      payload = jwt.decode(
          token, config.SECRET_KEY, algorithms=[config.ALGORITHM], options={'leeway': 99999999999}
      )
      token_data = schemas.TokenPayload(**payload)
    except (JWTError, ValidationError):
      raise credentials_exception
    user = models.User.get_user(db, id=token_data.sub)
    if not user:
      raise HTTPException(status_code=404, detail="User not found")
    return user